global using System.Globalization;
global using System.IO.Compression;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using GeoConvert;
global using GeoConvert.ImageSharp;
global using Microsoft.Win32;
